### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by joy002** [trdavidt/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
   - Missing a screenshot of you setting up keygen
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
   - Please includes the keystroke count and show how chained commands together can save our time.
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Good job:)

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by trdavidt** [comment]
Hello, I pushed a [new commit](https://github.com/trdavidt/cse15l-lab-reports/commit/385c1e44cfd9da1737e385afb11834e5b2fbda8b) to the lab reports repo with fixes to this issue. Will regrade requests be available on Gradescope soon?

**Comment by joy002** [comment]
Hi, yes the regrade requests should be available on the gradescope already. Remember to paste the link to your modified page on the regrade request, so I'll be able to regrade your lab report.
